export const REQUEST_STATION = 'REQUEST_STATION';
export const RECEIVE_STATION = 'RECEIVE_STATION';

export const REQUEST_STATIONS = 'REQUEST_STATIONS';
export const RECEIVE_STATIONS = 'RECEIVE_STATIONS';
export const CLEAR_STATIONS = 'CLEAR_STATIONS';

export const REQUEST_STATION_STATS = 'REQUEST_STATION_STATS';
export const RECEIVE_STATION_STATS = 'RECEIVE_STATION_STATS';

export const REQUEST_STATION_STATUS = 'REQUEST_STATION_STATUS';
export const RECEIVE_STATION_STATUS = 'RECEIVE_STATION_STATUS';
